// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/kysion/pay-share-library/internal/logic/order"
)
