// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/pay-share-library/pay_model/pay_dao/internal"
)

type OrderDao = dao_interface.TIDao[internal.OrderColumns]

func NewOrder(dao ...dao_interface.IDao) OrderDao {
	return (OrderDao)(internal.NewOrderDao(dao...))
}

var (
	Order = NewOrder()
)
