
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name:     "pay-share-library"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link: "pgsql:user=kuaimk password=Kuaimk23db host=192.168.1.105 port=5432 dbname=kuaimk_test sslmode=disable"
        tables: "kmk_order, "
        removePrefix: "kmk_, co_"
        descriptionTag:  true
        noModelComment:  true
        withTime: false

